---
apiVersion: v1
kind: Service
metadata:
  name: spring-rest-api
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"  # Load Balancer Interno
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"       # Network Load Balancer
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal" # (Opcional) Especifica que o LB é interno
  labels:
    name: spring-rest-api
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 8080        # Porta que será exposta
      targetPort: 8080  # Porta no container que receberá o tráfego
  selector:
    app: spring-rest-api  # Label selector para encontrar os pods corretos

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-rest-api
spec:
  selector:
    matchLabels:
      app: spring-rest-api
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-rest-api
    spec:
      containers:
        - name: spring-rest-api
          image: 793862496606.dkr.ecr.us-east-1.amazonaws.com/galega-ms-order-app:latest
          ports:
            - containerPort: 8080

          # Setting Enviornmental Variables
          env:
            # Setting Database host address from configMap
            - name: DATABASE_HOST
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: host

            - name: DATABASE_NAME
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: name

            # Setting Database name from configMap
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_user

            # Setting Database username from Secret
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password

            - name: SPRING_DATASOURCE_DRIVER-CLASS-NAME
              value: "org.postgresql.Driver"

            - name: MERCADOPAGO_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: mercadopago-credentials
                  key: access_key

            - name: MERCADOPAGO_PUBLIC_KEY
              valueFrom:
                configMapKeyRef:
                  name: mercadopago-credentials
                  key: public_key

            - name: LOGGING_LEVEL_ORG_FLYWAYDB
              value: DEBUG