---
apiVersion: v1
kind: Service
metadata:
  name: galega-ms-order
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-name: "galega-ms-order-lb"
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"  # Load Balancer Interno
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"       # Network Load Balancer
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internal" # (Opcional) Especifica que o LB é interno
  labels:
    name: galega-ms-order
spec:
  type: LoadBalancer
  ports:
    - name: web
      port: 6666        # Porta que será exposta
      targetPort: 6666  # Porta no container que receberá o tráfego
  selector:
    app: galega-ms-order # Label selector para encontrar os pods corretos

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: galega-ms-order
spec:
  selector:
    matchLabels:
      app: galega-ms-order
  replicas: 1
  template:
    metadata:
      labels:
        app: galega-ms-order
    spec:
      containers:
        - name: galega-ms-order
          image: 775370709632.dkr.ecr.us-east-1.amazonaws.com/galega-ms-order-app:latest
          ports:
            - containerPort: 6666

          # Setting Enviornmental Variables
          envFrom:
            - configMapRef:
                name: galega-ms-order-config