apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-conf
data:
  host: "POSTGRES_HOST_PLACEHOLDER"
  name: "POSTGRES_DB_PLACEHOLDER"

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
data:
  postgres_user: POSTGRES_USER_PLACEHOLDER
  postgres_password: POSTGRES_PASSWORD_PLACEHOLDER

---