apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-conf
data:
  host: "POSTGRES_HOST_PLACEHOLDER"
  name: "POSTGRES_DB_PLACEHOLDER"

---

apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
data:
  postgres_user: POSTGRES_USER_PLACEHOLDER
  postgres_password: POSTGRES_PASSWORD_PLACEHOLDER

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mercadopago-credentials
data:
  access_key: "TEST-4517379499194350-070720-7a234218d8d1d7fe49f0b99f6e21902c-449901113"
  public_key: "TEST-568883f9-e2de-4072-9c4b-54d28066b653"
