name: CI

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    services:
      sonarqube:
        image: sonarqube:9.9-community
        ports:
          - 9000:9000
        env:
          SONAR_JDBC_URL: jdbc:h2:mem:sonar;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
          SONAR_JDBC_USERNAME: sa
          SONAR_JDBC_PASSWORD: ""
        options: >-
          --health-cmd="curl -f http://localhost:9000/api/system/status || exit 1"
          --health-interval=5s
          --health-timeout=2s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with Gradle
        run: ./gradlew build -x test --no-daemon

      - name: SonarQube Scan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonarqube -Dsonar.projectKey=your_project_key -Dsonar.host.url=http://
